stages:
- build

variables:
    name: "UltimateStacker"
    suffex: "Legacy"
    path: "/builds/Songoda/$name"
    version: "1.1.6"

build:
  stage: build
  image: maven:3.5.3-jdk-8
  script:
    - find $path/ -type f -name "*.xml" -print0 | xargs -0 sed -i -e s/maven-version-number/$version/g
    - find $path/ -type f -name "*.yml" -print0 | xargs -0 sed -i -e s/maven-version-number/$version/g
    - mvn clean package
    - find $path/ -depth -path '*original*' -delete
    - mv -v $path/target/*.jar $path
  artifacts:
    name: $name-$suffex-$version
    paths:
    - "$path/*.jar"

